/// Flutter icons ChatApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ChatApp
///      fonts:
///       - asset: fonts/ChatApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons26pt {
  CustomIcons26pt._();

  static const _kFontFam = 'Icons26pt';

  static const IconData compose = const IconData(0xe803, fontFamily: _kFontFam);
}
